const test_qlrs = [
    "Chronic Depression",
    "Housing Insecurity",
    "Food Insecurity",
    "Clean Water Insecurity",
    "Lack of Primary Education access",
    "Lack of Secondary Education access",
    "Lack of Higher Education access",
    "Complete Blindness",
    "Total Blindness",
    "Near-total visual impairment",
    "Severe visual impairment",
    "Moderate visual impairment",
    "Deafness",
    "Severe hearing loss",
    "Moderate hearing loss",
    "Lack of religious freedom",
    "Forced Labor",
    "Sex Trafficking",
    "Lack of Access to Effective Medical Care",
    "Lack of Access to Electricity",
    "Lack of Internet Access",
    "Anorexia nervosa",
    "Bulimia nervosa",
    "Chronic Migraines",
    "Lack of Freedom of Movement",
    "Lack of Freedom of Thought",
    "Lack of Freedom of Speech",
    "Lack of Freedom of Assembly",
    "Lack of Freedom of Association",
];

module.exports = test_qlrs;